service: carbon-registry-services

provider:
  name: aws
  runtime: nodejs16.x
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  environment:
    NODE_ENV: ${opt:stage, 'dev'}
  iam:
    role: arn:aws:iam::909101490035:role/lambda-role
  vpc:
    subnetIds:
      - subnet-04c3a9dfd6c822bdc
      - subnet-05abb4287f3081602
    securityGroupIds:
      - sg-0bf65b90711ab2043

package:
  patterns:
    - "!node_modules/**"
    - ".env"
    - .env.${self:provider.stage}
    - "countries.json"
    - "regions.csv"
    - "src/i18n/**"

plugins:
  - "serverless-plugin-typescript"
  - serverless-plugin-optimize
  - serverless-offline
  # - serverless-ssm-fetch
#  - '@haftahave/serverless-ses-template'

params:
  local:
    depLayerArn1: arn:aws:lambda:us-west-2:111111111111:layer:layer:1
    depLayerArn2: arn:aws:lambda:us-west-2:111111111111:layer:layer:1

functions:
  national-api:
    timeout: 300
    handler: src/national-api/handler.handler
    events:
      - http:
          method: any
          path: /national/{any+}
      - http:
          method: any
          path: /national
    # ssmToEnvironment:
    #   - DB_PASSWORD
    #   - USER_JWT_SECRET
    #   - ADMIN_JWT_SECRET
    #   - SMTP_PASSWORD
    environment:
      NODE_PATH: "./:/opt/node_modules"
      DB_PASSWORD: perlin123!
      USER_JWT_SECRET: '1234'
      ADMIN_JWT_SECRET: '8654'
      SMTP_PASSWORD: BJPIbqCcoeRf87SFruI/Bl0Daz5hfB4o8DkKk4nB5y0D
    layers:
      - ${param:depLayerArn1}
      - ${param:depLayerArn2}

  analytics-api:
    timeout: 300
    handler: src/analytics-api/handler.handler
    events:
      - http:
          method: any
          path: /stats/{any+}
      - http:
          method: any
          path: /stats
    # ssmToEnvironment:
    #   - DB_PASSWORD
    #   - USER_JWT_SECRET
    #   - ADMIN_JWT_SECRET
    #   - SMTP_PASSWORD
    environment:
      NODE_PATH: "./:/opt/node_modules"
      DB_PASSWORD: perlin123!
      USER_JWT_SECRET: '1234'
      ADMIN_JWT_SECRET: '8654'
      SMTP_PASSWORD: BJPIbqCcoeRf87SFruI/Bl0Daz5hfB4o8DkKk4nB5y0D
    layers:
      - ${param:depLayerArn1}
      - ${param:depLayerArn2}

  replicator:
    timeout: 60
    handler: src/ledger-replicator/handler.handler
    events:
      - stream:
          arn: arn:aws:kinesis:us-east-1:909101490035:stream/carbon-stream-${self:provider.stage}
          batchSize: 2
          startingPosition: LATEST
          maximumRetryAttempts: 10
          enabled: true
    # ssmToEnvironment:
    #   - DB_PASSWORD
    #   - MAPBOX_PK
    environment:
      NODE_PATH: "./:/opt/node_modules"
      DB_PASSWORD: perlin123!
      MAPBOX_PK: 'pk.eyJ1IjoiaWdvci1wZXJsaW5uZXQiLCJhIjoiY2xrcnZlMXZpMWt0eDNka3llMGEyZGs0YSJ9.MoaYxDMv5zPJRUEN2lp0MQ'
    layers:
      - ${param:depLayerArn1}
      - ${param:depLayerArn2}

  data-importer:
    timeout: 60
    handler: src/data-importer/handler.handler
    events:
      - schedule:
          rate: cron(0 1 * * ? *)
          enabled: true
          input: 
            importTypes: ITMO_SYSTEM
    # ssmToEnvironment:
    #   - DB_PASSWORD
    #   - ITMO_API_KEY
    #   - ITMO_EMAIL
    #   - ITMO_PASSWORD
    environment:
      NODE_PATH: "./:/opt/node_modules"
      DB_PASSWORD: perlin123!
      ITMO_API_KEY: testkey123
      ITMO_EMAIL: aws@bioeconomy.co
      ITMO_PASSWORD: 1q2w3e4r5t6
    layers:
      - ${param:depLayerArn1}
      - ${param:depLayerArn2}

  -async-operations-handler:
    timeout: 60
    handler: src/async-operations-handler/handler.handler
    events:
      - sqs:
          arn: arn:aws:sqs:us-east-1:909101490035:AsyncQueue${self:provider.stage}.fifo
          batchSize: 10
    # ssmToEnvironment:
    #   - SMTP_PASSWORD
    #   - DB_PASSWORD
    #   - MRV_API_TOKEN
    environment:
      NODE_PATH: "./:/opt/node_modules"
      DB_PASSWORD: perlin123!
      SMTP_PASSWORD: BJPIbqCcoeRf87SFruI/Bl0Daz5hfB4o8DkKk4nB5y0D
      MRV_API_TOKEN: test123mrv!
    layers:
      - ${param:depLayerArn1}
      - ${param:depLayerArn2}

  setup:
    timeout: 60
    handler: src/setup/handler.handler
    # ssmToEnvironment:
    #   - DB_PASSWORD
    #   - SMTP_PASSWORD
    environment:
      NODE_PATH: "./:/opt/node_modules"
      DB_PASSWORD: perlin123!
      SMTP_PASSWORD: BJPIbqCcoeRf87SFruI/Bl0Daz5hfB4o8DkKk4nB5y0D
    layers:
      - ${param:depLayerArn1}
      - ${param:depLayerArn2}

  default:
    handler: src/shared/handler.handler
    events:
      - http:
          method: any
          path: /{any+}
    environment:
      NODE_PATH: "./:/opt/node_modules"
    layers:
      - ${param:depLayerArn1}
      - ${param:depLayerArn2}
custom:
  optimize:
    external: ["swagger-ui-dist"]
  # serverlessSsmFetch:
  #   DB_PASSWORD: /carbon-registry-services/dev/DB_PASSWORD~true
  #   USER_JWT_SECRET: /carbon-registry-services/dev/USER_JWT_SECRET~true
  #   ADMIN_JWT_SECRET: /carbon-registry-services/dev/ADMIN_JWT_SECRET~true
  #   SMTP_PASSWORD: /carbon-registry-services/dev/SES_PASSWORD~true
  #   MAPBOX_PK: /carbon-registry-services/dev/MAPBOX_PK~true
  #   ITMO_API_KEY: /carbon-registry-services/dev/ITMO_API_KEY~true
  #   ITMO_EMAIL: /carbon-registry-services/dev/ITMO_EMAIL~true
  #   ITMO_PASSWORD: /carbon-registry-services/dev/ITMO_PASSWORD~true
  #   MRV_API_TOKEN: /carbon-registry-services/dev/MRV_API_TOKEN~true
  # sesTemplates:
  #   addStage: true                             # Specifies whether to add stage to template name (default false)
  #   configFile: './src/shared/email/email.template.ts' # Config file path (default './ses-email-templates/index.js')
  #   region: 'us-east-1'
